# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout

      - restore_cache:
          keys:
            - docker-{{ checksum ".circleci/config.yml" }}--{{ checksum "docker-compose.yml" }}
          paths:
            - ~/caches/images.tar
      - run:
          name: Setup docker
          command: |
            if [ ! -f ~/caches/images.tar ]; then
              docker-compose build
              mkdir -p ~/caches
              docker save $(docker images | awk 'NR>=2 && ! /^<none>/{print $1}') -o ~/caches/images.tar
            fi
      - save_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}--{{ checksum "docker-compose.yml" }}
          paths:
            - ~/caches/images.tar

      - run:
          name: docker load
          command: |
            if [[ -e ~/caches/images.tar ]]; then
              docker load -i ~/caches/images.tar
            fi

      # docker build
      - run:
          name: up docker
          command: docker-compose up -d

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: docker-compose exec php composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # copy .env
      - run: cp .env.example .env

      - run: sleep 5
      - run: docker-compose exec php php artisan migrate:refresh --seed

      # exec tests!
      - run: docker-compose exec php ./vendor/bin/phpunit
