name: repository-backup
on:
  # schedule:
  #   - cron: '0 0 1 * *' # UTCで、毎月1日の00:00に実行（JSTで言うと朝9時）
  workflow_dispatch: # ブラウザからの手動実行も一応できるようにしておく。

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # リポジトリの全履歴を取得します。

      - run: |
          mkdir -p temp_dir  # 一時ディレクトリを作成
          tar -czvf temp_dir/source.tar.gz --exclude=temp_dir .  # 一時ディレクトリにアーカイブを作成
          mv temp_dir/source.tar.gz .  # アーカイブをカレントディレクトリに移動
          rm -rf temp_dir  # 一時ディレクトリを削除

      - uses: actions/upload-artifact@v4
        with:
          name: source-archive  # アーティファクトの名前
          path: source.tar.gz  # アップロードするファイルのパス
